# Generated by Django 2.1 on 2018-09-06 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('version', models.FloatField(default=1.0)),
                ('djangoVer', models.FloatField(default=2.0)),
                ('trainType', models.CharField(choices=[('VD', 'Video'), ('LV', 'Live'), ('DC', 'Document')], default='VD', max_length=2)),
                ('yearProd', models.DateTimeField(verbose_name='date created')),
                ('active', models.BooleanField(null=True)),
                ('imageCourse', models.ImageField(default=None, upload_to='')),
                ('hostedSite', models.CharField(max_length=65)),
                ('series', models.CharField(default='Inch by Inch', max_length=250)),
                ('last_accessed', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='trainings',
            field=models.ManyToManyField(default=False, to='yogicoder.Training'),
        ),
    ]
