# Generated by Django 2.1.1 on 2018-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.URLField(null=True),
        ),
    ]
