# Generated by Django 2.1.1 on 2018-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0002_training_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.URLField(default='Training In Development', null=True),
        ),
    ]
