# Generated by Django 2.1.1 on 2018-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0003_auto_20180911_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='courseID',
            field=models.CharField(default='C', max_length=500),
        ),
    ]
