# Generated by Django 2.1.1 on 2018-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0004_training_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='imageCourse',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.URLField(blank=True, default='Training In Development'),
        ),
    ]
