# Generated by Django 2.1.1 on 2018-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0005_auto_20180911_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.URLField(blank=True),
        ),
    ]
