# Generated by Django 2.1.1 on 2018-09-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogicoder', '0006_auto_20180911_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('student_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogicoder.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='imageCourse',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='training_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogicoder.Training'),
        ),
    ]
